### ISSUE TITLE
Add down for maintenance if no new daily contract has been deployed

### ISSUE THREAD

**Issue by chrismaree** [carboclan/dapp.honeylemon.market#85] opened 2020-05-28 21:49 UTC
In the event that a new contract has not been deployed the front end should say "down for maintenance"

**Comment by FSM1** [comment] 2020-05-28 21:54
Is there a way we can check this before the user connecting their wallet (instantiating the service)? Also, which call would I need to make to get the last contract deployed time? @andrei-anisimov @chrismaree I remember you mentioning something about this yesterday.

**Comment by FSM1** [comment] 2020-05-28 21:58
This is also a duplicate of #63

**Comment by FSM1** [comment] 2020-06-21 12:56
Resolved in #125

**Closed by FSM1** 2020-06-21 12:56 UTC
Labels: duplicate, enhancement
